version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/master -- docs/ .readthedocs.yaml src/;
        then
          exit 183;
        fi
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv tool install hatch
    - uv tool run hatch run docs:sphinx-build -T -b html -d docs/_build/doctrees docs $READTHEDOCS_OUTPUT/html
